/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-18 18:46:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@9/dist/sweetalert2.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style4.css\">\r\n");
      out.write("    <title> Remixology | Login & Registration</title>\r\n");
      out.write("    <style>@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');\r\n");
      out.write("	*{  \r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    padding: 0;\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	    font-family: 'Poppins', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	body{\r\n");
      out.write("	    background-image: linear-gradient(rgba(249, 243, 234,0.3),rgba(244, 230, 210,0.3),rgba(213, 170, 157,0.3));\r\n");
      out.write("	    background-size: cover;\r\n");
      out.write("	    background-repeat: no-repeat;\r\n");
      out.write("	    background-attachment: fixed;\r\n");
      out.write("	    overflow: hidden;\r\n");
      out.write("	    \r\n");
      out.write("	}\r\n");
      out.write("	.wrapper{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    justify-content: center;\r\n");
      out.write("	    align-items: center;\r\n");
      out.write("	    min-height: 110vh;\r\n");
      out.write("	    background: rgba(244, 230, 210,0.4);\r\n");
      out.write("	    margin-bottom: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-logo img{\r\n");
      out.write("	    height: 200px;\r\n");
      out.write("	    text-align: left;\r\n");
      out.write("	    display: inline;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-logo{\r\n");
      out.write("	    width:1100px;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    margin-top: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.nav{\r\n");
      out.write("	    position: fixed;\r\n");
      out.write("	    top: 0;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    justify-content: space-around;\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	    height: 100px;\r\n");
      out.write("	    line-height: 100px;\r\n");
      out.write("	    background: linear-gradient(rgba(249, 243, 234,0.9), transparent);\r\n");
      out.write("	    z-index: 100;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-menu ul{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-menu ul li{\r\n");
      out.write("	    list-style-type: none;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-menu ul li .link{\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    font-weight: 500;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    padding-bottom: 15px;\r\n");
      out.write("	    margin: 0 25px;\r\n");
      out.write("	}\r\n");
      out.write("	.link:hover, .active{\r\n");
      out.write("	    border-bottom: 2px solid #be872c;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-button .btn{\r\n");
      out.write("	    width: 130px;\r\n");
      out.write("	    height: 40px;\r\n");
      out.write("	    font-weight: 500;\r\n");
      out.write("	    background: rgba(224, 176, 148, 0.4);\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    border-radius: 30px;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    transition: .3s ease;\r\n");
      out.write("	}\r\n");
      out.write("	.btn:hover{\r\n");
      out.write("	    background: rgba(224, 176, 148, 0.3);\r\n");
      out.write("	}\r\n");
      out.write("	#registerBtn{\r\n");
      out.write("	    margin-left: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn.white-btn{\r\n");
      out.write("	    background: rgba(255, 255, 255, 0.7);\r\n");
      out.write("	}\r\n");
      out.write("	.btn.btn.white-btn:hover{\r\n");
      out.write("	    background: rgba(255, 255, 255, 0.5);\r\n");
      out.write("	}\r\n");
      out.write("	.nav-menu-btn{\r\n");
      out.write("	    display: none;\r\n");
      out.write("	}\r\n");
      out.write("	.form-box{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    align-items: center;\r\n");
      out.write("	    justify-content: center;\r\n");
      out.write("	    width: 512px;\r\n");
      out.write("	    height: 820px;\r\n");
      out.write("	    overflow: hidden;\r\n");
      out.write("	    z-index: 2;\r\n");
      out.write("	}\r\n");
      out.write("	.login-container{\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    left: 4px;\r\n");
      out.write("	    width: 500px;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    flex-direction: column;\r\n");
      out.write("	    transition: .5s ease-in-out;\r\n");
      out.write("	}\r\n");
      out.write("	.register-container{\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    right: -520px;\r\n");
      out.write("	    width: 500px;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    flex-direction: column;\r\n");
      out.write("	    transition: .5s ease-in-out;\r\n");
      out.write("	}\r\n");
      out.write("	.top span{\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    font-size: small;\r\n");
      out.write("	    padding: 10px 0;\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	.top span a{\r\n");
      out.write("	    font-weight: 500;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    margin-left: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	header{\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    font-size: 30px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    padding: 10px 0 30px 0;\r\n");
      out.write("	}\r\n");
      out.write("	.two-forms{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    gap: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.input-field{\r\n");
      out.write("	    font-size: 15px;\r\n");
      out.write("	    background: rgba(224, 176, 148,0.2);\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    height: 50px;\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	    padding: 0 10px 0 45px;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    border-radius: 30px;\r\n");
      out.write("	    outline: none;\r\n");
      out.write("	    transition: .2s ease;\r\n");
      out.write("	}\r\n");
      out.write("	.input-field:hover, .input-field:focus{\r\n");
      out.write("	    background: rgba(249, 243, 234,0.2);\r\n");
      out.write("	}\r\n");
      out.write("	::-webkit-input-placeholder{\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	}\r\n");
      out.write("	.input-box i{\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    top: -35px;\r\n");
      out.write("	    left: 17px;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	}\r\n");
      out.write("	.submit{\r\n");
      out.write("	    font-size: 15px;\r\n");
      out.write("	    font-weight: 500;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    height: 45px;\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    border-radius: 30px;\r\n");
      out.write("	    outline: none;\r\n");
      out.write("	    background: rgba(224, 176, 148,0.9);\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    transition: .3s ease-in-out;\r\n");
      out.write("	}\r\n");
      out.write("	.submit:hover{\r\n");
      out.write("	    background: rgba(224, 176, 148,0.9);\r\n");
      out.write("	    box-shadow: 1px 5px 7px 1px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	}\r\n");
      out.write("	.two-col{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    justify-content: space-between;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	    font-size: small;\r\n");
      out.write("	    margin-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.two-col .one{\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	    gap: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.two label a{\r\n");
      out.write("	    text-decoration: none;\r\n");
      out.write("	    color: #be872c;\r\n");
      out.write("	}\r\n");
      out.write("	.two label a:hover{\r\n");
      out.write("	    text-decoration: underline;\r\n");
      out.write("	}\r\n");
      out.write("	.error-msg {\r\n");
      out.write("	    color: red;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	@media only screen and (max-width: 786px){\r\n");
      out.write("	    .nav-button{\r\n");
      out.write("	        display: none;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu.responsive{\r\n");
      out.write("	        top: 100px;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu{\r\n");
      out.write("	        position: absolute;\r\n");
      out.write("	        top: -800px;\r\n");
      out.write("	        display: flex;\r\n");
      out.write("	        justify-content: center;\r\n");
      out.write("	        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        height: 90vh;\r\n");
      out.write("	        backdrop-filter: blur(20px);\r\n");
      out.write("	        transition: .3s;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu ul{\r\n");
      out.write("	        flex-direction: column;\r\n");
      out.write("	        text-align: center;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu-btn{\r\n");
      out.write("	        display: block;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu-btn i{\r\n");
      out.write("	        font-size: 25px;\r\n");
      out.write("	        color: #be872c;\r\n");
      out.write("	        padding: 10px;\r\n");
      out.write("	        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("	        border-radius: 50%;\r\n");
      out.write("	        cursor: pointer;\r\n");
      out.write("	        transition: .3s;\r\n");
      out.write("	    }\r\n");
      out.write("	    .nav-menu-btn i:hover{\r\n");
      out.write("	        background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	@media only screen and (max-width: 540px) {\r\n");
      out.write("	    .wrapper{\r\n");
      out.write("	        min-height: 100vh;\r\n");
      out.write("	    }\r\n");
      out.write("	    .form-box{\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        height: 500px;\r\n");
      out.write("	    }\r\n");
      out.write("	    .register-container, .login-container{\r\n");
      out.write("	        width: 100%;\r\n");
      out.write("	        padding: 0 20px;\r\n");
      out.write("	    }\r\n");
      out.write("	    .register-container .two-forms{\r\n");
      out.write("	        flex-direction: column;\r\n");
      out.write("	        gap: 0;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"wrapper\">\r\n");
      out.write("    <nav class=\"nav\">\r\n");
      out.write("        <div class=\"nav-logo\">\r\n");
      out.write("            <p><img src=\"Orange Simple Food Logo (4).png\" /></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-button\">\r\n");
      out.write("            <button class=\"btn white-btn\" id=\"loginBtn\" onclick=\"login()\">Sign In</button>\r\n");
      out.write("            <button class=\"btn\" id=\"registerBtn\" onclick=\"register()\">Sign Up</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav-menu-btn\">\r\n");
      out.write("            <i class=\"bx bx-menu\" onclick=\"myMenuFunction()\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"form-box\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-container\" id=\"login\">\r\n");
      out.write("            <div class=\"top\">\r\n");
      out.write("                <span>Don't have an account? <a href=\"#\" onclick=\"register()\">Sign Up</a></span>\r\n");
      out.write("                <header>Login</header>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"Login.jsp\" method=\"POST\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"email\" class=\"input-field\" placeholder=\"Email\" name=\"email\">\r\n");
      out.write("                    <i class=\"bx bx-user\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"password\" class=\"input-field\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("                    <i class=\"bx bx-lock-alt\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"submit\" class=\"submit\" value=\"Sign In\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"two-col\">\r\n");
      out.write("                <div class=\"one\">\r\n");
      out.write("                    <input type=\"checkbox\" id=\"login-check\">\r\n");
      out.write("                    <label for=\"login-check\"> Remember Me</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"two\">\r\n");
      out.write("                    <label><a href=\"forgotPassword.jsp\">Forgot password?</a></label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"register-container\" id=\"register\">\r\n");
      out.write("            <div class=\"top\">\r\n");
      out.write("                <span>Have an account? <a href=\"#\" onclick=\"login()\">Login</a></span>\r\n");
      out.write("                <header>Sign Up</header>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form method=\"POST\" id=\"reg\" name=\"registrationForm\" action=\"Register.jsp\" onsubmit=\"return validateAndSubmit(event)\">\r\n");
      out.write("                <div class=\"two-forms\">\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" placeholder=\"Firstname\" name=\"firstname\">\r\n");
      out.write("                        <i class=\"bx bx-user\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <input type=\"text\" class=\"input-field\" placeholder=\"Lastname\" name=\"lastname\">\r\n");
      out.write("                        <i class=\"bx bx-user\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"email\" class=\"input-field\" placeholder=\"Email\" name=\"email\">\r\n");
      out.write("                    <i class=\"bx bx-envelope\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                <label for=\"password\"></label>\r\n");
      out.write("                    <input type=\"password\" id=\"password1\" class=\"input-field\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("                    <i class=\"bx bx-lock-alt\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"password\" id=\"confirmPassword\" class=\"input-field\" placeholder=\"Confirm Password\" name=\"confirmPassword\">\r\n");
      out.write("                    <i class=\"bx bx-lock-alt\"></i>\r\n");
      out.write("                    <div id=\"confirmPasswordError\" class=\"error-msg\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                <label for=\"birthdate\">Birthdate</label>\r\n");
      out.write("                    <input type=\"date\" class=\"input-field\" name=\"birthdate\" id=\"birthdate\">\r\n");
      out.write("                    <i class='bx bx-cake' ></i>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"radio\" class=\"input-field\" name=\"gender\" value=\"Male\" style=\"height: auto; width:auto;\"><label style=\"color: #be872c; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif; \">Male</label><br/>\r\n");
      out.write("                    <input type=\"radio\" class=\"input-field\" name=\"gender\" value=\"Female\" style=\"height: auto; width:auto;\"><label style=\"color: #be872c; font-size:large; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\">Female</label>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <input type=\"submit\" class=\"submit\" value=\"Register\" name=\"Register\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"two-col\">\r\n");
      out.write("                <div class=\"one\">\r\n");
      out.write("                    <input type=\"checkbox\" id=\"register-check\">\r\n");
      out.write("                    <label for=\"register-check\"> Remember Me</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"two\">\r\n");
      out.write("                    <label><a href=\"#\">Terms & conditions</a></label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function validateAndSubmit(event) {\r\n");
      out.write("    event.preventDefault(); // Prevent form submission until validated\r\n");
      out.write("\r\n");
      out.write("    // Password validation\r\n");
      out.write("    var passwordInput = document.getElementById(\"password1\").value;\r\n");
      out.write("    var passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$/; // At least one lowercase, one uppercase, one digit, one special character, and 8 characters long\r\n");
      out.write("    if (!passwordRegex.test(passwordInput)) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            position: 'center',\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Invalid password',\r\n");
      out.write("            text: 'Password must be at least 8 characters long and contain at least one lowercase letter, one uppercase letter, one digit, and one special character',\r\n");
      out.write("            confirmButtonColor: '#3085d6',\r\n");
      out.write("            confirmButtonText: 'OK',\r\n");
      out.write("        });\r\n");
      out.write("        return false; // Prevent form submission\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Birthdate validation\r\n");
      out.write("    var birthdateInput = document.getElementById(\"birthdate\").value;\r\n");
      out.write("    var birthdate = new Date(birthdateInput);\r\n");
      out.write("    if (isNaN(birthdate.getTime()) || birthdate.getFullYear() > 2010) {\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            position: 'center',\r\n");
      out.write("            icon: 'error',\r\n");
      out.write("            title: 'Invalid birthdate',\r\n");
      out.write("            text: 'Birthdate must be from the year 2010 or later',\r\n");
      out.write("            confirmButtonColor: '#3085d6',\r\n");
      out.write("            confirmButtonText: 'OK',\r\n");
      out.write("        });\r\n");
      out.write("        return false; // Prevent form submission\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // If both validations pass, submit the form\r\n");
      out.write("    document.getElementById(\"reg\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   \r\n");
      out.write("   function myMenuFunction() {\r\n");
      out.write("    var i = document.getElementById(\"navMenu\");\r\n");
      out.write("\r\n");
      out.write("    if(i.className === \"nav-menu\") {\r\n");
      out.write("        i.className += \" responsive\";\r\n");
      out.write("    } else {\r\n");
      out.write("        i.className = \"nav-menu\";\r\n");
      out.write("    }\r\n");
      out.write("   }\r\n");
      out.write("   </script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    var a = document.getElementById(\"loginBtn\");\r\n");
      out.write("    var b = document.getElementById(\"registerBtn\");\r\n");
      out.write("    var x = document.getElementById(\"login\");\r\n");
      out.write("    var y = document.getElementById(\"register\");\r\n");
      out.write("\r\n");
      out.write("    function login() {\r\n");
      out.write("        x.style.left = \"4px\";\r\n");
      out.write("        y.style.right = \"-520px\";\r\n");
      out.write("        a.className += \" white-btn\";\r\n");
      out.write("        b.className = \"btn\";\r\n");
      out.write("        x.style.opacity = 1;\r\n");
      out.write("        y.style.opacity = 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function register() {\r\n");
      out.write("        x.style.left = \"-510px\";\r\n");
      out.write("        y.style.right = \"5px\";\r\n");
      out.write("        a.className = \"btn\";\r\n");
      out.write("        b.className += \" white-btn\";\r\n");
      out.write("        x.style.opacity = 0;\r\n");
      out.write("        y.style.opacity = 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var password = document.getElementById(\"password\").value;\r\n");
      out.write("        var confirmPassword = document.getElementById(\"confirmPassword\").value;\r\n");
      out.write("        if (password != confirmPassword) {\r\n");
      out.write("            document.getElementById(\"confirmPasswordError\").innerHTML = \"Passwords do not match!\";\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
