/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-18 22:35:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Ingredients_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Product Filter And Search</title>\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body style=\"color:#be872c; background-color:#f4e6d2;\">\r\n");
      out.write("  				<a href='Homaepage.jsp'>home</a>\r\n");
      out.write("    <style>\r\n");
      out.write("    * {\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-family: \"Poppins\", sans-serif;\r\n");
      out.write("  }\r\n");
      out.write("  body {\r\n");
      out.write("    background-color: #d5aa9d;\r\n");
      out.write("  }\r\n");
      out.write("  .wrapper {\r\n");
      out.write("    width: 95%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("  }\r\n");
      out.write("  #search-container {\r\n");
      out.write("    margin: 1em 0;\r\n");
      out.write("  }\r\n");
      out.write("  #search-container input {\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    width: 40%;\r\n");
      out.write("    border-bottom: 2px solid #110f29;\r\n");
      out.write("    padding: 1em 0.3em;\r\n");
      out.write("  }\r\n");
      out.write("  #search-container input:focus {\r\n");
      out.write("    border-bottom-color: white;\r\n");
      out.write("  }\r\n");
      out.write("  #search-container button {\r\n");
      out.write("    padding: 1em 2em;\r\n");
      out.write("    margin-left: 1em;\r\n");
      out.write("    background-color: #be872c;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    \r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    margin-top: 0.5em;\r\n");
      out.write("  }\r\n");
      out.write("  .button-value {\r\n");
      out.write("    border: 2px solid white;\r\n");
      out.write("    padding: 1em 2.2em;\r\n");
      out.write("    border-radius: 3em;\r\n");
      out.write("    background-color: #be872c;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("  }\r\n");
      out.write("  .active {\r\n");
      out.write("    background-color: #be872c;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("  }\r\n");
      out.write("  #products {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: auto auto auto;\r\n");
      out.write("    grid-column-gap: 1.5em;\r\n");
      out.write("    padding: 2em 0;\r\n");
      out.write("  }\r\n");
      out.write("  .card {\r\n");
      out.write("  	display: inline-block;\r\n");
      out.write("    background-color: #be872c;\r\n");
      out.write("    max-width: 18em;\r\n");
      out.write("    margin:0.5em;\r\n");
      out.write("    margin-top: 1em;\r\n");
      out.write("    \r\n");
      out.write("    padding: 1em;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: 1em 2em 2.5em rgba(1, 2, 68, 0.08);\r\n");
      out.write("  }\r\n");
      out.write("  .image-container {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("  }\r\n");
      out.write("  img {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("    height: 15em;\r\n");
      out.write("  }\r\n");
      out.write("  .container {\r\n");
      out.write("    padding-top: 1em;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("  }\r\n");
      out.write("  .container h5 {\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("  }\r\n");
      out.write("  .hide {\r\n");
      out.write("    display: none;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  @media screen and (max-width: 720px) {\r\n");
      out.write("    img {\r\n");
      out.write("      max-width: 100%;\r\n");
      out.write("      object-fit: contain;\r\n");
      out.write("      height: 10em;\r\n");
      out.write("    }\r\n");
      out.write("    .card {\r\n");
      out.write("      max-width: 10em;\r\n");
      out.write("      margin-top: 1em;\r\n");
      out.write("    }\r\n");
      out.write("    #products {\r\n");
      out.write("      grid-template-columns: auto auto;\r\n");
      out.write("      grid-column-gap: 1em;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("    </style>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("      <div id=\"search-container\">\r\n");
      out.write("        <input\r\n");
      out.write("          type=\"search\"\r\n");
      out.write("          id=\"search-input\"\r\n");
      out.write("          placeholder=\"Search product name here..\"\r\n");
      out.write("        />\r\n");
      out.write("        <button id=\"search\">Search</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"buttons\">\r\n");
      out.write("        <button class=\"button-value\" onclick=\"filterProduct('all')\">All</button>\r\n");
      out.write("        <button class=\"button-value\" onclick=\"filterProduct('Vegetable')\">\r\n");
      out.write("            Vegetable\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"button-value\" onclick=\"filterProduct('Fruit')\">\r\n");
      out.write("          Fruit\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"button-value\" onclick=\"filterProduct('Spice')\">\r\n");
      out.write("          Spice\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"button-value\" onclick=\"filterProduct('Protein')\">\r\n");
      out.write("            Protein\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"button-value\" onclick=\"filterProduct('Liquid')\">\r\n");
      out.write("            Liquid\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"button-value\" onclick=\"filterProduct('Other')\">\r\n");
      out.write("            other\r\n");
      out.write("          </button>\r\n");
      out.write("          <form id=\"product-form\" action=\"ingredientsController.jsp\">\r\n");
      out.write("        <div id=\"products\"></div>\r\n");
      out.write("        <div id=\"submit-container\">\r\n");
      out.write("          <button id=\"submit-button\" class=\"button-value\">Submit</button>\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("      <!--  <div id=\"products\"></div>\r\n");
      out.write("    </div>-->\r\n");
      out.write("    <script>\r\n");
      out.write("    let products = {\r\n");
      out.write("    data: [\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Banana\",\r\n");
      out.write("            category: \"Fruit\",\r\n");
      out.write("            price: \"0.49\",\r\n");
      out.write("            image: \"banana.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Carrot\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"0.69\",\r\n");
      out.write("            image: \"carrot.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Apple\",\r\n");
      out.write("            category: \"Fruit\",\r\n");
      out.write("            price: \"0.79\",\r\n");
      out.write("            image: \"apple.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Lemon\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"0.59\",\r\n");
      out.write("            image: \"lemon.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Onion\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"0.39\",\r\n");
      out.write("            image: \"onion.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Garlic\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"1.29\",\r\n");
      out.write("            image: \"garlic.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Strawberry\",\r\n");
      out.write("            category: \"Fruit\",\r\n");
      out.write("            price: \"1.29\",\r\n");
      out.write("            image: \"strawberry.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Broccoli\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"1.49\",\r\n");
      out.write("            image: \"broccoli.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Tomato\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"0.89\",\r\n");
      out.write("            image: \"tomato.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Cucumber\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"0.79\",\r\n");
      out.write("            image: \"cucumber.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Ginger\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"2.99\",\r\n");
      out.write("            image: \"ginger.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Cinnamon\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"3.49\",\r\n");
      out.write("            image: \"cinamon.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Parsley\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"3.99\",\r\n");
      out.write("            image: \"prsley.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Vinegar\",\r\n");
      out.write("            category: \"Liquid\",\r\n");
      out.write("            price: \"3.99\",\r\n");
      out.write("            image: \"vinegar.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Coriander\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"1.99\",\r\n");
      out.write("            image: \"coriander.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Bay Leaf\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"2.79\",\r\n");
      out.write("            image: \"bay-leaf.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Rosemary\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"3.49\",\r\n");
      out.write("            image: \"rosemary.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Curry\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"2.99\",\r\n");
      out.write("            image: \"curry.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"7 Spices\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"5.49\",\r\n");
      out.write("            image: \"seven-spices.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Salt\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"1.29\",\r\n");
      out.write("            image: \"salt.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Paprika\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"2.29\",\r\n");
      out.write("            image: \"paprika.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        {\r\n");
      out.write("            productName: \"Pepper\",\r\n");
      out.write("            category: \"Vegetable\",\r\n");
      out.write("            price: \"1.79\",\r\n");
      out.write("            image: \"pepper.jpg\"\r\n");
      out.write("        },\r\n");
      out.write("        \r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Chicken Breast\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"3.99\",\r\n");
      out.write("                image: \"chicken-breast.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Tofu\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"2.49\",\r\n");
      out.write("                image: \"tofu.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Lean Beef Steak\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"6.99\",\r\n");
      out.write("                image: \"lean-beef-steak.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Eggs\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"2.29\",\r\n");
      out.write("                image: \"eggs.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"fish\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"3.29\",\r\n");
      out.write("                image: \"fish.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"tuna\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"2.29\",\r\n");
      out.write("                image: \"tuna.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Greek Yogurt\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"greek-yogurt.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cottage Cheese\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"3.49\",\r\n");
      out.write("                image: \"cottage-cheese.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Quinoa\",\r\n");
      out.write("                category: \"Protein\",\r\n");
      out.write("                price: \"3.79\",\r\n");
      out.write("                image: \"quinoa.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Lentils\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"lentils.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Milk\",\r\n");
      out.write("                category: \"Liquid\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"milk.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Oil\",\r\n");
      out.write("                category: \"Liquid\",\r\n");
      out.write("                price: \"2.00\",\r\n");
      out.write("                image: \"oil.jpg\"\r\n");
      out.write("            },{\r\n");
      out.write("                productName: \"olive oil\",\r\n");
      out.write("                category: \"Liquid\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"olive.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Water\",\r\n");
      out.write("                category: \"Liquid\",\r\n");
      out.write("                price: \"0.99\",\r\n");
      out.write("                image: \"water.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Pasta\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"pasta.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Bread\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"2.49\",\r\n");
      out.write("                image: \"bread.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Butter\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"3.49\",\r\n");
      out.write("                image: \"butter.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cheese\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"4.99\",\r\n");
      out.write("                image: \"cheese.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"chicken stock\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"4.99\",\r\n");
      out.write("                image: \"chicken-stock.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Yogurt\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"1.79\",\r\n");
      out.write("                image: \"yougurt.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cumin\",\r\n");
      out.write("                category: \"Spice\",\r\n");
      out.write("                price: \"0.79\",\r\n");
      out.write("                image: \"cumin.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Mango\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"mango.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Grapes\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"2.49\",\r\n");
      out.write("                image: \"grapes.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Pineapple\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"pineapple.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Watermelon\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"3.99\",\r\n");
      out.write("                image: \"watermelon.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Kiwi\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.49\",\r\n");
      out.write("                image: \"kiwi.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Pear\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"0.89\",\r\n");
      out.write("                image: \"pear.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Peach\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.39\",\r\n");
      out.write("                image: \"peach.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Blueberry\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"2.99\",\r\n");
      out.write("                image: \"blueberry.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cherry\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"2.79\",\r\n");
      out.write("                image: \"cherry.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Raspberry\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"3.49\",\r\n");
      out.write("                image: \"raspberry.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cantaloupe\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"2.99\",\r\n");
      out.write("                image: \"cantaloupe.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Apricot\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.79\",\r\n");
      out.write("                image: \"apricot.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Plum\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.69\",\r\n");
      out.write("                image: \"plum.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Coconut\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"coconut.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Dragon Fruit\",\r\n");
      out.write("                category: \"Fruit\",\r\n");
      out.write("                price: \"4.99\",\r\n");
      out.write("                image: \"dragon-fruit.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Baking powder\",\r\n");
      out.write("                category: \"Spice\",\r\n");
      out.write("                price: \"0.79\",\r\n");
      out.write("                image: \"baking-powder.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Toast\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"2.79\",\r\n");
      out.write("                image: \"toast.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Cereal\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"3.99\",\r\n");
      out.write("                image: \"cereal.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Basmati Rice\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"3.99\",\r\n");
      out.write("                image: \"basmati-rice.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Brown Rice\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"2.49\",\r\n");
      out.write("                image: \"brown-rice.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"White Rice\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"1.99\",\r\n");
      out.write("                image: \"rice.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Barley\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"2.99\",\r\n");
      out.write("                image: \"barley.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("                productName: \"Couscous\",\r\n");
      out.write("                category: \"Other\",\r\n");
      out.write("                price: \"3.49\",\r\n");
      out.write("                image: \"couscous.jpg\"\r\n");
      out.write("            },        \r\n");
      out.write("            {\r\n");
      out.write("            productName: \"black Pepper\",\r\n");
      out.write("            category: \"Spice\",\r\n");
      out.write("            price: \"1.79\",\r\n");
      out.write("            image: \"black-pepper.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            {\r\n");
      out.write("            productName: \"Orange\",\r\n");
      out.write("            category: \"Fruit\",\r\n");
      out.write("            price: \"0.79\",\r\n");
      out.write("            image: \"orange.jpg\"\r\n");
      out.write("            },\r\n");
      out.write("            ],\r\n");
      out.write("          };\r\n");
      out.write("    const productForm = document.getElementById(\"product-form\"); \r\n");
      out.write("    for (let i of products.data) {\r\n");
      out.write("    	let checkbox = document.createElement(\"input\");\r\n");
      out.write("   	    checkbox.setAttribute(\"type\", \"checkbox\");\r\n");
      out.write("   	    checkbox.setAttribute(\"name\", \"selected\");\r\n");
      out.write("   	    checkbox.setAttribute(\"value\", i.productName.toLowerCase());\r\n");
      out.write("   	    checkbox.classList.add(\"product-checkbox\");\r\n");
      out.write("   	    \r\n");
      out.write("        let card = document.createElement(\"div\");\r\n");
      out.write("        let div=document.getElementById(\"products\");\r\n");
      out.write("        card.classList.add(\"card\", i.category, \"hide\");\r\n");
      out.write("        let imgContainer = document.createElement(\"div\");\r\n");
      out.write("        imgContainer.classList.add(\"image-container\");\r\n");
      out.write("        let image = document.createElement(\"img\");\r\n");
      out.write("        image.setAttribute(\"src\", i.image);\r\n");
      out.write("        imgContainer.style.display = \"inline-block\";\r\n");
      out.write("        image.addEventListener(\"click\", () => {\r\n");
      out.write("            let checkbox = document.getElementById(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.productName.toLowerCase()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("-checkbox`);\r\n");
      out.write("            checkbox.checked = !checkbox.checked;\r\n");
      out.write("        });\r\n");
      out.write("        imgContainer.appendChild(image);\r\n");
      out.write("        card.appendChild(imgContainer);\r\n");
      out.write("        let container = document.createElement(\"div\");\r\n");
      out.write("        container.classList.add(\"container\");\r\n");
      out.write("\r\n");
      out.write("        let name = document.createElement(\"h5\");\r\n");
      out.write("        name.classList.add(\"product-name\");\r\n");
      out.write("        name.innerText = i.productName.toUpperCase();\r\n");
      out.write("\r\n");
      out.write("        let price = document.createElement(\"h6\");\r\n");
      out.write("        //price.innerText = \"$\" + i.price;\r\n");
      out.write("\r\n");
      out.write("        container.appendChild(name);\r\n");
      out.write("        container.appendChild(price);\r\n");
      out.write("        card.appendChild(container);\r\n");
      out.write("        card.appendChild(checkbox); // Append checkbox to the form\r\n");
      out.write("        productForm.appendChild(card); \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function filterProduct(value) {\r\n");
      out.write("        let buttons = document.querySelectorAll(\".button-value\");\r\n");
      out.write("        buttons.forEach((button) => {\r\n");
      out.write("          if (value.toUpperCase() == button.innerText.toUpperCase()) {\r\n");
      out.write("            button.classList.add(\"active\");\r\n");
      out.write("          } else {\r\n");
      out.write("            button.classList.remove(\"active\");\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      \r\n");
      out.write("        let elements = document.querySelectorAll(\".card\");\r\n");
      out.write("        elements.forEach((element) => {\r\n");
      out.write("          if (value == \"all\") {\r\n");
      out.write("            element.classList.remove(\"hide\");\r\n");
      out.write("          } else {\r\n");
      out.write("            if (element.classList.contains(value)) {\r\n");
      out.write("              element.classList.remove(\"hide\");\r\n");
      out.write("            } else {\r\n");
      out.write("              element.classList.add(\"hide\");\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      //Search button click\r\n");
      out.write("      document.getElementById(\"search\").addEventListener(\"click\", () => {\r\n");
      out.write("        //initializations\r\n");
      out.write("        let searchInput = document.getElementById(\"search-input\").value;\r\n");
      out.write("        let elements = document.querySelectorAll(\".product-name\");\r\n");
      out.write("        let cards = document.querySelectorAll(\".card\");\r\n");
      out.write("      \r\n");
      out.write("        //loop through all elements\r\n");
      out.write("        elements.forEach((element, index) => {\r\n");
      out.write("          //check if text includes the search value\r\n");
      out.write("          if (element.innerText.includes(searchInput.toUpperCase())) {\r\n");
      out.write("            //display matching card\r\n");
      out.write("            cards[index].classList.remove(\"hide\");\r\n");
      out.write("          } else {\r\n");
      out.write("            //hide others\r\n");
      out.write("            cards[index].classList.add(\"hide\");\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("      // Trigger search on Enter key press\r\n");
      out.write("    document.getElementById(\"search-input\").addEventListener(\"keypress\", (event) => {\r\n");
      out.write("        if (event.key === \"Enter\") {\r\n");
      out.write("            event.preventDefault(); // Prevent form submission\r\n");
      out.write("            document.getElementById(\"search\").click(); // Trigger the search button click\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    document.getElementById(\"submit-button\").addEventListener(\"click\", function() {\r\n");
      out.write("    	  // Submit the form\r\n");
      out.write("    	  document.querySelector(\"form\").submit();\r\n");
      out.write("    	});\r\n");
      out.write("\r\n");
      out.write("      //Initially display all products\r\n");
      out.write("      window.onload = () => {\r\n");
      out.write("        filterProduct(\"all\");\r\n");
      out.write("      };\r\n");
      out.write("        </script>\r\n");
      out.write("      </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
